install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages('leaflet')
source("https://bioconductor.org/biocLite.R")
biocLite("MSnbase")
